### ISSUE TITLE
Certain license classifiers incorrectly claim OSI approval status

### ISSUE THREAD

**Issue by richardfontana** [pypa/trove-classifiers#183] opened 2024-07-03 01:51 UTC
The following license classifiers incorrectly claim Open Source Initiative (OSI) approval status:

"License :: OSI Approved :: European Union Public Licence 1.0 (EUPL 1.0)"

"License :: OSI Approved :: GNU Free Documentation License (FDL)"

There may be others but those were the ones I quickly caught. In several additional cases, a license classifier claims OSI approval where the license classifier is ambiguous (typically because it can refer plausibly to more than one license associated with a name, and where one version of a license may have been OSI approved but not an earlier version). 

I suppose the existence of problems of this sort might justify use of SPDX identifiers as I understand is called for in https://peps.python.org/pep-0639/
and indeed the issue of ambiguous license classifiers is noted in that PEP.

cc: @jlovejoy who may find this issue of interest

**Comment by di** [comment] 2024-07-03 01:55
There are many more, please see #17 for more details.

**Comment by di** [comment] 2024-07-14 22:03
Closing as a duplicate of #17.

**Closed by di** 2024-07-14 22:03 UTC
